//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.30 at 01:13:18 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example/springbootsoapws/api/userWs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.springbootsoapwsclient.api.user;
